package:
  name: mypackage
  version: 0.0.1

build:
  number: 0
  script: python -m pip install . -vv --no-deps --no-build-isolation

source:
  path: .

requirements:
  build: 
    - python<3.11s
    - setuptools 
    - pip
    
  run:
    - python<3.11
    - conda-forge::rdkit
    - tmap::tmap
